name: Status Check

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main

jobs:
  status-check:
    runs-on: ubuntu-latest
    name: Check status
    steps:
    - uses: actions/checkout@v2
      env:
        CI: true
        PAGES: ${{ secrets.PAGES }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check status
      id: check_status
      shell: bash
      run: |
        mkdir -p logs
        IFS="\n" read -ra ODKAZY <<< "${{ secrets.PAGES }}"
        for ODKAZ in "${ODKAZY[@]}"; do
          IFS='=' read -ra odkaz <<< "$ODKAZ"
          (echo -n $(date '+%Y-%m-%d %H:%M:%S')", ";curl --write-out '%{response_code}, %{time_total}' --silent --insecure --output /dev/null ${odkaz[1]};echo) >> logs/${odkaz[0]}.log
        done
        find logs/ -iname '*.log' > logs/files.cfg
    - name: Commit and push files
      id: commit
      run: |
        git config --local user.email "tomas-dockal@seznam.cz"
        git config --local user.name "Izzak"
        git add -A --force logs/
        git commit -am '[Automated] Update Status Logs'
        git push
      shell: bash