name: Status Check

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main

jobs:
  status-check:
    runs-on: ubuntu-latest
    name: Check status
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check status LOAD BALANCER
      id: check_load_balancer
      shell: bash
      run: |
        mkdir -p logs
        IFS='|' read -ra ODKAZY <<< "${{ secrets.LOAD_BALANCER }}"
        for ODKAZ in "${ODKAZY[@]}"; do
          IFS='=' read -ra odkaz <<< "$ODKAZ"
          (echo -n $(date '+%Y-%m-%d %H:%M:%S')", ";curl --write-out '%{response_code}, %{time_total}' --silent --insecure --output /dev/null ${odkaz[1]};echo) >> logs/${odkaz[0]}.log
        done

    - name: Check status SERVER 1
      id: check_server_1
      shell: bash
      run: |
        mkdir -p logs
        IFS='|' read -ra ODKAZY <<< "${{ secrets.SERVER_1 }}"
        for ODKAZ in "${ODKAZY[@]}"; do
          IFS='=' read -ra odkaz <<< "$ODKAZ"
          (echo -n $(date '+%Y-%m-%d %H:%M:%S')", ";curl --write-out '%{response_code}, %{time_total}' --silent --insecure --output /dev/null ${odkaz[1]};echo) >> logs/${odkaz[0]}.log
        done

    - name: Check status SERVER 2
      id: check_server_2
      shell: bash
      run: |
        mkdir -p logs
        IFS='|' read -ra ODKAZY <<< "${{ secrets.SERVER_2 }}"
        for ODKAZ in "${ODKAZY[@]}"; do
          IFS='=' read -ra odkaz <<< "$ODKAZ"
          (echo -n $(date '+%Y-%m-%d %H:%M:%S')", ";curl --write-out '%{response_code}, %{time_total}' --silent --insecure --output /dev/null ${odkaz[1]};echo) >> logs/${odkaz[0]}.log
        done

    - name: Check status SERVER 3
      id: check_server_3
      shell: bash
      run: |
        mkdir -p logs
        IFS='|' read -ra ODKAZY <<< "${{ secrets.SERVER_3 }}"
        for ODKAZ in "${ODKAZY[@]}"; do
          IFS='=' read -ra odkaz <<< "$ODKAZ"
          (echo -n $(date '+%Y-%m-%d %H:%M:%S')", ";curl --write-out '%{response_code}, %{time_total}' --silent --insecure --output /dev/null ${odkaz[1]};echo) >> logs/${odkaz[0]}.log
        done

    - name: Generate filesname
      id: filesname
      shell: bash
      run: |
        find logs/ -iname '*.log' > logs/files.cfg

    - name: Commit and push files
      id: commit
      run: |
        git config --local user.email "tomas-dockal@seznam.cz"
        git config --local user.name "Izzak"
        git add -A --force logs/
        git commit -am '[Automated] Update Status Logs'
        git push
      shell: bash