name: Check status

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main

jobs:
  status-check:
    runs-on: ubuntu-latest
    name: Check status
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check servers status
      id: check_status
      run: |
        bash ./check.sh "${{ secrets.PAGES }}"
    - name: Commit and push files
      id: commit
      run: |
        git config --local user.email "tomas-dockal@seznam.cz"
        git config --local user.name "Izzak"
        git add -A --force logs/
        git commit -am '[Automated] Update Status Logs'
        git push