name: Status Check

# Controls when the action will run.
on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - main


jobs:
  status-check:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
    - uses: actions/checkout@v2
    - name: Check all sites
      id: check_script
      shell: bash
      run: |
        mkdir -p logs
        IFS=';' read -ra ODKAZY <<< "${{ secrets.PAGES }}"
        for odkaz in "${ODKAZY[@]}"; do
          (echo -n $(date '+%d/%m/%Y %H:%M:%S')", ";curl --write-out '%{response_code}, %{time_total}' --silent --insecure --output /dev/null $odkaz;echo) >> logs/$odkaz.txt
        done
    - name: Commit and push files
      id: commit
      run: |
        git config --local user.email "tomas-dockal@seznam.cz"
        git config --local user.name "Izzak"
        git add -A --force logs/
        git commit -am '[Automated] Update Status Check Logs'
        git push
      shell: bash